name: First Job

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Environment name'
        required: true
        type: string
      agent:
        description: 'Agent'
        required: true
        type: choice
        options:
          - ecs
          - master
          - UI_Docker
          - prod_node
          - any

jobs:
  trigger-cfn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger CFN Workflow
        id: trigger_cfn
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/cfn.yml/dispatches \
            -d '{
                  "ref": "main",
                  "inputs": {
                    "env_name": "${{ github.event.inputs.env_name }}",
                    "agent": "${{ github.event.inputs.agent }}"
                  }
                }'

      - name: Running deploy statement
        run: |
          echo "This is running after the cloudformation workflow succeeded"
