name: CFN Workflow

on:
  workflow_call:
    inputs:
      env_name:
        description: enviornment name
        type: string
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment name'
        required: true
        type: string
      agent:
        description: 'Agent'
        required: true
        type: choice
        options:
          - ecs
          - master
          - UI_Docker
          - prod_node
          - any

jobs:
  validate:
    uses: srikanth-1612/single-env-deployment/.github/workflows/ampm.yml@main
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deployment Step
        run: |
          echo "Running deployment for env_name: ${{ github.event.inputs.Environment }} and agent: ${{ github.event.inputs.agent }}"
          # Your deployment logic here
