name: CFN Workflow

on:
  workflow_call:
    inputs:
      env_name:
        description: enviornment name
        type: string
  workflow_dispatch:
    inputs:
      deploy_env:
        description: enviornment name
        type: environment

jobs:
  validate:
    uses: srikanth-1612/reusable-workflows/.github/workflows/ampm.yml@master
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deployment Step
        run: |
          echo "Running deployment for env_name: ${{ github.event.inputs.env_name }} and agent: ${{ github.event.inputs.agent }}"
          # Your deployment logic here
