name: Deploy S3 Bucket via CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate CloudFormation template
        uses: srikanth-1612/reusable-workflows/.github/workflows/merging-checks.yml@main
        with:
          template-path: s3-bucket.yml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file path/to/your/s3-bucket.yml \
            --stack-name MyS3BucketStack \
            --capabilities CAPABILITY_NAMED_IAM
          # Optionally, wait for the deployment to complete
          aws cloudformation wait stack-create-complete --stack-name MyS3BucketStack
